spring:
  profiles:
    active:
      - dev
  thymeleaf:
    prefix: classpath:/templates
    mode: LEGACYHTML5
    cache: false
mybatis:
  config-locations: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/UserMapper.xml
  type-aliases-package: com.whm.pojo
  
